### ISSUE TITLE
effect.check() modify events when construct is for document and has resolver

### ISSUE THREAD

**Issue by wataru-chocola** [micromark/micromark#86]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

micromark

### Link to runnable example

https://github.com/wataru-chocola/report-micromark-20210827

### Steps to reproduce

Run my PoC.

```console
$ git clone https://github.com/wataru-chocola/report-micromark-20210827
$ cd report-micromark-20210827
$ npm install
$ npx node index.js
```

### Expected behavior

`document` constructs are invoked twice in `micromark/lib/initialize/document.js` :

1. from `checkNewContainers` state

    ```javascript
    return effects.check(
      containerConstruct,
      thereIsANewContainer,
      thereIsNoNewContainer
    )(code)
    ```

2. from `documentContinued`

    ````javascript
    return effects.attempt(
      containerConstruct,
      containerContinue,
      flowStart
    )(code)
    ````

And I expect the first invocation `effect.check(...)` doesn't make any modifications on events.

```javascript
 * @property {Attempt} check
 *   Attempt, then revert.
```

### Actual behavior

`effect.check()` does modify events if construct is for document and has resolver.

My construct in PoC code dumps context.events at the start.
On 1st run (from `effects.check`), we see the correct events which are generated by previous tokenization.

```
+ initialize tokenizer (runCount: 1)
+ previous events
[ 'enter', 'chunkFlow', 'term\n' ]
[ 'exit', 'chunkFlow', 'term\n' ]
+ run resolverTo
```

But on 2nd run (from `effects.attempt`), events are modified by resolver in the previous `check` execution.

```
+ initialize tokenizer (runCount: 2)
+ previous events
[ 'enter', 'defListTerm', 'term\n' ]
[ 'enter', 'chunkFlow', 'term\n' ]
```

**Comment by wooorm** [comment]
If you really want to do this, I think you might be better of looking at footnote definitions for the “container” part, those colons, see: https://github.com/micromark/micromark-extension-footnote/blob/561f958a9bf33a1f3f0d2f61b370199dbff2610b/dev/lib/syntax.js#L45-L49.

But, honestly, I think this is a bad designed syntax extension, that doesn’t match how markdown works otherwise.

Better solutions in my opinion are either directives (**Arbitrary extension mechanism** in [§ Extending markdown](https://github.com/micromark/micromark#extending-markdown)):

```markdown
:::definition[Orange]
The fruit of an evergreen tree of the genus Citrus.
:::

:::definition[Apple]
*   Pomaceous fruit of plants of the genus Malus in 
    the family Rosaceae.

*   An American computer company.
:::

:::definition[Term 1, Term 2]
Definition a
:::
```

Or (ab)using lists (**Using and abusing markdown to add new meaning** in [§ Extending markdown](https://github.com/micromark/micromark#extending-markdown)):

```markdown
*   **Orange**

    The fruit of an evergreen tree of the genus Citrus.

*   **Apple**

    *   Pomaceous fruit of plants of the genus Malus in 
        the family Rosaceae.

    *   An American computer company.

*   **Term 1**
    **Term 2**

    Definition a
```

**Comment by wataru-chocola** [comment]
@wooorm Thank you, I'll take a look at `micromark-extension-footnote`.


> And indeed, resolve changes the events.

Well, the behavior about `effect.check` / `effect.attempt` / `resolveTo` seems a bit inconsistent for me.

* `effect.attempt` (`onsuccessfulconstruct`) calls `addResult` which invokes `resolveTo` to modify events. This is straightfoward.
* `effect.check` (`onsuccessfulcheck`) doesn't do, but if its argument construct calls `effect.attempt` inside it, it would run `resolveTo` and modify events consequently.

If this behavior is not a problem, please close this issue.


And thank you for your help!

**Comment by wataru-chocola** [comment]
Just FYI.

Thanks to your kind help, I've finally published my extension package.

* [micromark-extension-definition-list](https://www.npmjs.com/package/micromark-extension-definition-list)
* [mdast-util-definition-list](https://www.npmjs.com/package/mdast-util-definition-list)
* [remark-definition-list](https://www.npmjs.com/package/remark-definition-list)


Regards

**Comment by wooorm** [comment]
Awesome, glad it worked!

I looked through the readmes and here are some suggestions, If you’re interested:

- The `remark-definition-list` usage example uses `./index`, but should probably import the package name?
- For remark plugins, I recommend using a default export for the plugin. This means they can be used by the engine (`remark-cli`), such as with `remark input.md --use remark-definition-list --output output.md` (only with a default can the engine/cli “find” the plugin).
All other plugins also use a default export, so it’ll help users because there is a single API
You can export the same value as both a named export and a default export btw, so it can be a minor release!
- You can add the plugin to the List of plugins in remark’s readme https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins
- Same for the extension here, maybe a new “Community extensions” heading, with this extension, under the current list of extensions? https://github.com/micromark/micromark#list-of-extensions
- There’s a typo in the micromark extension readme: `Definitio` instead of `Definition`. Also `develepment` -> `development`!

👋

**Comment by wooorm** [comment]
Going to close this, as this particular thing is intended. Maybe some docs somewhere might be good, and I’d appreciate a PR for that if you have a suggestion!

**Comment by wataru-chocola** [comment]
@wooorm 

I published new version including your suggestions, bug fix, some improvement.
Can I ask you to add my plugin and extension to remark / micromark readme?

> * You can add the plugin to the List of plugins in remark’s readme https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins
> * Same for the extension here, maybe a new “Community extensions” heading, with this extension, under the current list of extensions? https://github.com/micromark/micromark#list-of-extensions

**Comment by wooorm** [comment]
Done!
